; problem to debug pddl
(define (problem pursuer-prob)
    (:domain pursuer-evader)
    (:objects
        l1 l2 l3 l4 l5 l6 - waypoint
        l0 - gate
    )
    (:init
        (at r1 l1)
        (at r2 l3)

        ; (evading)
        (pursuing)

        (= (total-cost) 0)

        (near l1 l2)
        (= (distance l1 l2) 8)
        (= (distance l2 l1) 8)
        (near l1 l4)
        (= (distance l1 l4) 8)
        (= (distance l4 l1) 8)
        (near l2 l3)
        (= (distance l2 l3) 7)
        (= (distance l3 l2) 7)
        (near l2 l5)
        (= (distance l2 l5) 5)
        (= (distance l5 l2) 5)
        (near l3 l6)
        (= (distance l3 l6) 10)
        (= (distance l6 l3) 10)
        (near l4 l5)
        (= (distance l4 l5) 5)
        (= (distance l5 l4) 5)
        (near l4 l0)
        (= (distance l4 l0) 5)
        (= (distance l0 l4) 5)
        (near l5 l6)
        (= (distance l5 l6) 5)
        (= (distance l6 l5) 5)
        (near l5 l0)
        (= (distance l5 l0) 15)
        (= (distance l0 l5) 15)
        (near l6 l0)
        (= (distance l6 l0) 20)
        (= (distance l0 l6) 29)

        (= (evader-cost l3) 0)
        (= (evader-cost l2) 7)
        (= (evader-cost l5) 12)
        (= (evader-cost l4) 17)
        (= (evader-cost l0) 22)

        (= (evader-cost l1) -1)
        (= (evader-cost l6) -1)
    )
    (:goal
        ; (evaded r2)
        (caught r1)
    )
    (:metric minimize(total-cost)
    )
)
